a<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>What Can I Do?</title>
    <link rel="stylesheet" href="srpp.css">
</head>
<body>
     <!-- Navbar -->
     <header>
        <nav class="navbar">
            <a href="#" class="logo">videos on plastic<span>.</span></a>
        </nav>
    </header>
<
<script>
fetch('navbar.php')
    .then(response => response.text())
    .then(data => document.querySelector('header').innerHTML = data);
    fetch('footer.php')
    .then(response => response.text())
    .then(data => document.querySelector('footer').innerHTML = data);


    </script>
    
    
    <main class="main-content">
        
            <p>Actions you take in your daily life can make a difference for the planet.</p>
     
        
            <!-- Example Article Block -->
            <div class="article-item">
                <img src="s1.jpg" alt="Recycle" class="article-image">
                <div class="article-content">
                    <h2>Use the Bag Bin at Your Supermarket Entrance</h2>
                    <p>Not only can actual bags (which, really, there should be very few of) go in the bag bin, but thin films like what covers hummus pots can go in as well. We are making contact with local supermarkets in our area to try to get more details as to just what can and can't go into these materials streams. Stay tuned (or help support the work we are doing).</p><a href="https://resource-recycling.com/recycling/2021/10/19/why-carton-recycling-has-stalled-in-one-state/?utm_medium=email&utm_source=internal&utm_campaign=Oct+22+FR">More Info</a>
                </div>
            </div>

            <div class="article-item">
                <img src="s2.jpg" alt="Shopping" class="article-image">
                <div class="article-content">
                    <h2>Bring Your Own Cutlery(BYOC)</h2>
                    <p>For restaurants that only have single-use plastics for cutlery, there are some great kits available that have a fork, knife and spoon (or chopsticks) in a small container that will slip into a purse or backpack. Talk to the restaurant manager about their unsustainable practices, but barring a change at the source, you can displace some plastic waste by using your BYOC from your kit. It is also a visible way of triggering people to think. People at the next table will see your conscientiousness and perhaps think more about actions that they could take. Your friendly website administrator frequently gets "That is so cool! Where'd you get that?" comments when he whips out his reusable kit. (Pro tip: go for a plastic or aluminum case rather than cloth ones so that the dirties can go back in after the meal).
                        Just one of many places to get your.</p><a href="https://www.amazon.com/s?k=reusable+travel+utensils+plastic+case&crid=23I084PV3Q880&sprefix=reusable+travel+utensils+plastic+case%2Caps%2C137&ref=nb_sb_noss">More Info</a>

                </div>
            </div>

            <div class="article-item">
                <img src="s3.jpg" alt="Recycle" class="article-image">
                <div class="article-content">
                    <h2>Bring Your Own Metal Bottle</h2>
                    <p>An oldie, but a goodie. Not only are you displacing the plastic that would have gone into single-use bottles, but you are also displacing the carbon generated by the transportation of a low-value product across large distances. As a bonus, you don't have to worry about harmful chemicals leaching from the plastic into your water on those hot summer days.</p><a href="https://www.amazon.com/s?k=tiffins&crid=2F1XB4H04NNZN&sprefix=tiffins%2Caps%2C107&ref=nb_sb_noss">More Info</a>
                </div>
            </div>

            <div class="article-item">
                <img src="s4.jpg" alt="Recycle" class="article-image">
                <div class="article-content">
                    <h2>Bring Your Own Take-Away Container</h2>
                    <p>Carry your lunch to work?Frequent a restaurant that has such big portions that you know you are going to want a doggie bag? Rather than use the Styrofoam (polystyrene) or plastic take-away containers, you could bring your own reusable takeaway vessels. Reusable metal Tiffins brought to yo</p><a href="https://resource-recycling.com/recycling/2021/10/19/why-carton-recycling-has-stalled-in-one-state/?utm_medium=email&utm_source=internal&utm_campaign=Oct+22+FR">More Info</a>
                </div>
            </div>

            <div class="article-item">
                <img src="s5.jpg" alt="Recycle" class="article-image">
                <div class="article-content">
                    <h2>Spread the World</h2>
                    <p>Like what we are trying to accomplish? Spread the word. You can share our content by using the social media buttons on many of our pages, or generate a message of your own. Found a great product that displaces plastic production or which has conscientious packaging? Lead others there with a post. A restaurant you frequent has finally stopped using Styrofoam or plastic cutlery? Congratulate them with a shout out and send them some business as a reward.</p><a href="https://resource-recycling.com/recycling/2021/10/19/why-carton-recycling-has-stalled-in-one-state/?utm_medium=email&utm_source=internal&utm_campaign=Oct+22+FR">More Info</a>
                </div>
            </div>

            <div class="article-item">
                <img src="s6.jpg" alt="Recycle" class="article-image">
                <div class="article-content">
                    <h2>Don't wear glitter</h2>
                    <p>Most glitter is basically microplastics that find their way into waterways, the food chain, and sometimes into our bodies.Read more about glitter as micropla</p><a href="https://resource-recycling.com/recycling/2021/10/19/why-carton-recycling-has-stalled-in-one-state/?utm_medium=email&utm_source=internal&utm_campaign=Oct+22+FR">More Info</a>
                 </div>
            </div>

            <div class="article-item">
                <img src="s3.jpg" alt="Recycle" class="article-image">
                <div class="article-content">
                    <h2>Don't wear plastic</h2>
                    <p>Synthetic fabrics by whatever name they go by - nylon, polyester, spandex, acrylic, etc. are just plastic. Cotton also has its own issues, such as water use, but at least when you wash a cotton shirt, plastic microfibers won't go down the drain and into our rivers and oceans.Check out the Vox's piece on micro</p><a href="https://resource-recycling.com/recycling/2021/10/19/why-carton-recycling-has-stalled-in-one-state/?utm_medium=email&utm_source=internal&utm_campaign=Oct+22+FR">More Info</a>
                </div>
            </div>

            <div class="article-item">
                <img src="s4.jpg" alt="Recycle" class="article-image">
                <div class="article-content">
                    <h2>But milk in jugs not in packets</h2>
                    <p>At least in Austin, those milk (or oat milk, almond milk, etc. - with or without the rigid plastic caps) cartons are not recyclable and should go into the brown/landfill bin. Likewise for juice boxes, soup cartons, and similar products. The general theme here is complexity. Paper is easy to recycle and plastic can be relatively easy, but fuse the two together into multi-layered materials and they become much more difficult to handle, leading to either higher costs for a low-value material or contamination of the materials recovery facility (MRF's) output. Other municipalities do accept them (Dallas, Houston, and San Antonio, for example), but as a general rule, simpler mono- material packaging is always better from a recycling standpoint.
                    Read more on headaches faced by c</p><a href="https://resource-recycling.com/recycling/2021/10/19/why-carton-recycling-has-stalled-in-one-state/?utm_medium=email&utm_source=internal&utm_campaign=Oct+22+FR">More Info</a>

                </div>
            </div>
          
          
            
            <!-- Add more article items as needed -->
        
    </main>

    <footer class="footer">
        <p>&copy; 2024 Planet Protection Project</p>
    </footer>
</body>
</html>

